---
- name: Generate WireGuard configuration file
  template:
    src: wireguard.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  notify: restart WireGuard

- name: Enable the VPN at boot-time
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
